# -*- coding: utf-8 -*-
"""Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STOo0AzE4T_7huVufKHcvS6jJImFx8GK
"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Financials.csv')
df.head()

import pandas as pd

# Replace spaces with underscores and make column names lowercase
df.columns = [col.strip().lower().replace(" ", "_") for col in df.columns]
df.head()

import sqlite3

# Create SQLite connection
conn = sqlite3.connect("sales_data.db")

# Store DataFrame into SQLite
df.to_sql('sales', conn, if_exists='replace', index=False)

query = """
SELECT
    product,
    SUM(units_sold) AS total_units_sold,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
FROM sales
GROUP BY product
"""

summary_df = pd.read_sql_query(query, conn)
print("Sales Summary by Product:")
print(summary_df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
summary_df.plot(kind='bar', x='product', y='total_sales', legend=False, color='orange')
plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

conn.close()